version: "3"

services:
  dtourais:
    restart: always
    image: dtourais/extracteur:1.0.0
    volumes:
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /home/xx:/home/Txx
    working_dir: /home/Txx
    command: /usr/sbin/sshd -D
    deploy:
      resources:
        limits:
          memory: 20G
    shm_size: '20G'
